 services:
  - type: web
    name: n8n
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: N8N_PORT
        value: 5678
      - key: N8N_HOST
        value: n8n-render-docker-qvym.onrender.com
      - key: WEBHOOK_URL
        value: https://n8n-render-docker-qvym.onrender.com/
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        value: deinStarkesPasswort

      # PostgreSQL Verbindung
      - key: DB_TYPE
        value: postgres
      - key: DB_POSTGRESDB_HOST
        value: dpg-d1drjqmmcj7s73bdvnsg-a
      - key: DB_POSTGRESDB_PORT
        value: "5432"
      - key: DB_POSTGRESDB_DATABASE
        value: n8n_db_8stj
      - key: DB_POSTGRESDB_USER
        value: n8n_db_8stj_user
      - key: DB_POSTGRESDB_PASSWORD
        value: 05KwhGNkJdDAon98TrczwIWBh55pOXGd

